import type { CatalogItem } from "./types";

const ES = ["Spain"];
const MX = ["Mexico"];
const AR = ["Argentina"];
const CO = ["Colombia"];

export const SPANISH: CatalogItem[] = [
  // Series
  {
    key: "es/ministerio-del-tiempo", name: "The Ministry of Time", kind: "tv_show", year: 2015, finale: 2020, countries: ES, rating: "TV-14", minutes: 70,
    original: ["El Ministerio del Tiempo", "es"],
    desc: "Agents of a secret Spanish government ministry step through doors in time to keep history on track.",
    local: ["serie española de ciencia ficción y aventuras", "es"],
    tags: ["science_fiction", "drama", "comedy", "time_travel", "bureaucracy", "workplace", "witty"],
    pop: 0.62, cities: { madrid: 0.9, "mexico-city": 0.4, "buenos-aires": 0.35, bogota: 0.3 }, fans: ["severance", "the-office"], by: "Javier y Pablo Olivares",
  },
  {
    key: "es/paquita-salas", name: "Paquita Salas", kind: "tv_show", year: 2016, finale: 2019, countries: ES, rating: "TV-MA", minutes: 30,
    desc: "A washed-up Madrid talent agent fights to keep her tiny agency and her last clients.",
    local: ["comedia española sobre una representante de actores", "es"],
    tags: ["comedy", "mockumentary", "workplace", "showbiz", "witty", "quirky"],
    pop: 0.55, cities: { madrid: 0.85, "mexico-city": 0.35, "buenos-aires": 0.3 }, fans: ["fleabag", "the-office"], by: "Javier Calvo, Javier Ambrossi",
  },
  {
    key: "es/casa-de-las-flores", name: "The House of Flowers", kind: "tv_show", year: 2018, finale: 2020, countries: MX, rating: "TV-MA", minutes: 30,
    original: ["La casa de las flores", "es"],
    desc: "A wealthy Mexico City family's flower-shop business hides one scandal after another.",
    local: ["serie mexicana de comedia negra", "es"],
    tags: ["comedy", "dark_comedy", "drama", "family", "family_business", "wealth", "satire", "witty"],
    pop: 0.7, cities: { "mexico-city": 0.9, madrid: 0.5, "buenos-aires": 0.45, bogota: 0.5 }, fans: ["succession", "fleabag"], by: "Manolo Caro",
  },
  {
    key: "es/club-de-cuervos", name: "Club de Cuervos", kind: "tv_show", year: 2015, finale: 2019, countries: MX, rating: "TV-MA", minutes: 48,
    desc: "Two siblings fight over the football club their father left behind in a small Mexican city.",
    tags: ["comedy", "drama", "family_business", "power_struggle", "sports", "satire", "witty"],
    pop: 0.6, cities: { "mexico-city": 0.8, madrid: 0.3, bogota: 0.4 }, fans: ["succession", "ted-lasso"], by: "Gaz Alazraki",
  },
  {
    key: "es/casa-de-papel", name: "Money Heist", kind: "tv_show", year: 2017, finale: 2021, countries: ES, rating: "TV-MA", minutes: 50,
    original: ["La casa de papel", "es"],
    desc: "A mastermind called the Professor leads a crew through a long siege inside Spain's Royal Mint.",
    local: ["serie española de atracos", "es"],
    tags: ["thriller", "crime", "heist", "tense"],
    pop: 0.97, cities: { madrid: 0.8, "mexico-city": 0.85, "buenos-aires": 0.8, bogota: 0.85 }, fans: ["breaking-bad"], by: "Álex Pina",
  },
  {
    key: "es/elite", name: "Elite", kind: "tv_show", year: 2018, finale: 2024, countries: ES, rating: "TV-MA", minutes: 50,
    original: ["Élite", "es"],
    desc: "Three scholarship students at an exclusive private school get caught up in a murder.",
    tags: ["thriller", "drama", "mystery", "school", "wealth", "coming_of_age", "young_adult"],
    pop: 0.88, cities: { madrid: 0.75, "mexico-city": 0.8, "buenos-aires": 0.7, bogota: 0.75 }, fans: ["stranger-things"],
  },
  {
    key: "es/chicas-del-cable", name: "Cable Girls", kind: "tv_show", year: 2017, finale: 2020, countries: ES, rating: "TV-14", minutes: 50,
    original: ["Las chicas del cable", "es"],
    desc: "Four women at Madrid's national telephone company in the late 1920s fight for their independence.",
    tags: ["period_drama", "drama", "romance", "workplace", "friendship"],
    pop: 0.72, cities: { madrid: 0.7, "mexico-city": 0.6, "buenos-aires": 0.5, bogota: 0.55 }, fans: ["pride-and-prejudice", "gilmore-girls"],
  },
  {
    key: "es/valeria", name: "Valeria", kind: "tv_show", year: 2020, finale: 2023, countries: ES, rating: "TV-MA", minutes: 40,
    desc: "A novelist in Madrid with writer's block leans on her three best friends while her marriage wobbles.",
    tags: ["romantic_comedy", "comedy", "drama", "friendship", "city_life", "romance", "warm"],
    pop: 0.6, cities: { madrid: 0.75, "mexico-city": 0.55, "buenos-aires": 0.45 }, fans: ["gilmore-girls", "normal-people", "fleabag"],
  },
  {
    key: "es/alta-mar", name: "High Seas", kind: "tv_show", year: 2019, finale: 2020, countries: ES, rating: "TV-14", minutes: 50,
    original: ["Alta mar", "es"],
    desc: "Two sisters sailing from Spain to Rio de Janeiro in the 1940s investigate a murder on board.",
    tags: ["mystery", "period_drama", "whodunit", "thriller", "romance"],
    pop: 0.6, cities: { madrid: 0.6, "mexico-city": 0.5, "buenos-aires": 0.45 }, fans: ["orient-express", "knives-out"],
  },
  {
    key: "es/bienvenidos-a-eden", name: "Welcome to Eden", kind: "tv_show", year: 2022, finale: 2023, countries: ES, rating: "TV-MA", minutes: 45,
    original: ["Bienvenidos a Edén", "es"],
    desc: "Five young people invited to a party on a remote island find a community that won't let them leave.",
    tags: ["thriller", "mystery", "island", "cult", "young_adult", "eerie"],
    pop: 0.6, cities: { madrid: 0.6, "mexico-city": 0.55 }, fans: ["severance", "stranger-things"],
  },
  {
    key: "es/cien-anos", name: "One Hundred Years of Solitude", kind: "tv_show", year: 2024, countries: CO, rating: "TV-MA", minutes: 60,
    original: ["Cien años de soledad", "es"],
    desc: "Seven generations of the Buendía family in the town of Macondo, filmed in Colombia in Spanish.",
    local: ["serie colombiana basada en la novela de García Márquez", "es"],
    tags: ["drama", "magical_realism", "family", "period_drama", "slow_burn"],
    pop: 0.75, cities: { bogota: 0.9, "mexico-city": 0.7, "buenos-aires": 0.6, madrid: 0.6 }, fans: ["pride-and-prejudice", "normal-people"],
  },
  {
    key: "es/eternauta", name: "The Eternaut", kind: "tv_show", year: 2025, countries: AR, rating: "TV-MA", minutes: 55,
    original: ["El Eternauta", "es"],
    desc: "A deadly snowfall kills most of Buenos Aires, and a group of friends fights to survive what comes next.",
    tags: ["science_fiction", "thriller", "dystopia", "survival", "tense"],
    pop: 0.8, cities: { "buenos-aires": 0.95, "mexico-city": 0.5, madrid: 0.5, bogota: 0.45 }, fans: ["severance", "stranger-things"], by: "Bruno Stagnaro",
  },
  {
    key: "es/monarca", name: "Monarca", kind: "tv_show", year: 2019, finale: 2021, countries: MX, rating: "TV-MA", minutes: 50,
    desc: "The heirs of a Mexican tequila business fight over the family company.",
    tags: ["drama", "family_business", "wealth", "power_struggle", "tense"],
    pop: 0.5, cities: { "mexico-city": 0.8, madrid: 0.3 }, fans: ["succession", "the-godfather"],
  },
  {
    key: "es/luis-miguel", name: "Luis Miguel: The Series", kind: "tv_show", year: 2018, finale: 2021, countries: MX, rating: "TV-14", minutes: 50,
    original: ["Luis Miguel, la serie", "es"],
    desc: "The life of Mexican pop star Luis Miguel, from child singer to stadium headliner.",
    tags: ["drama", "biopic", "music_industry", "family", "music"],
    pop: 0.7, cities: { "mexico-city": 0.9, madrid: 0.5, "buenos-aires": 0.55, bogota: 0.6 }, fans: ["taylor-swift", "la-la-land"],
  },
  {
    key: "es/juana-ines", name: "Juana Inés", kind: "tv_show", year: 2016, countries: MX, rating: "TV-14", minutes: 50,
    desc: "The life of the 17th-century poet Sor Juana Inés de la Cruz in colonial Mexico.",
    tags: ["period_drama", "drama", "biopic"],
    pop: 0.45, cities: { "mexico-city": 0.7, madrid: 0.3 }, fans: ["pride-and-prejudice"],
  },
  // Films
  {
    key: "es/laberinto-del-fauno", name: "Pan's Labyrinth", kind: "movie", year: 2006, countries: ["Spain", "Mexico"], rating: "R", minutes: 118,
    original: ["El laberinto del fauno", "es"],
    desc: "In 1944 Spain, a girl escapes into a dark fairy-tale world hidden near her stepfather's camp.",
    tags: ["fantasy", "drama", "fairy_tale", "dark"],
    pop: 0.9, cities: { "mexico-city": 0.8, madrid: 0.8, "buenos-aires": 0.6, bogota: 0.6 }, fans: ["spirited-away", "stranger-things", "arcane"], by: "Guillermo del Toro",
  },
  {
    key: "es/roma", name: "Roma", kind: "movie", year: 2018, countries: MX, rating: "R", minutes: 135,
    desc: "A year in the life of a live-in housekeeper for a middle-class family in 1970s Mexico City.",
    tags: ["drama", "family", "black_and_white", "slow_burn", "nostalgic"],
    pop: 0.8, cities: { "mexico-city": 0.85, madrid: 0.5 }, fans: ["normal-people"], by: "Alfonso Cuarón",
  },
  {
    key: "es/relatos-salvajes", name: "Wild Tales", kind: "movie", year: 2014, countries: ["Argentina", "Spain"], rating: "R", minutes: 122,
    original: ["Relatos salvajes", "es"],
    desc: "Six short stories about ordinary people pushed over the edge, played as pitch-black comedy.",
    tags: ["dark_comedy", "comedy", "thriller", "anthology", "satire"],
    pop: 0.75, cities: { "buenos-aires": 0.9, madrid: 0.7, "mexico-city": 0.7, bogota: 0.55 }, fans: ["fleabag", "succession", "knives-out"], by: "Damián Szifron",
  },
  {
    key: "es/nueve-reinas", name: "Nine Queens", kind: "movie", year: 2000, countries: AR, rating: "R", minutes: 114,
    original: ["Nueve reinas", "es"],
    desc: "Two Buenos Aires con men try to sell a forged sheet of rare stamps in a single day.",
    tags: ["crime", "thriller", "con_artist", "heist", "witty"],
    pop: 0.6, cities: { "buenos-aires": 0.85, madrid: 0.5, "mexico-city": 0.4 }, fans: ["knives-out", "breaking-bad"], by: "Fabián Bielinsky",
  },
  {
    key: "es/volver", name: "Volver", kind: "movie", year: 2006, countries: ES, rating: "R", minutes: 121,
    desc: "Two sisters in Madrid and La Mancha deal with a family secret and the return of their mother.",
    tags: ["drama", "comedy", "dark_comedy", "family", "warm"],
    pop: 0.75, cities: { madrid: 0.8, "mexico-city": 0.55, "buenos-aires": 0.5 }, fans: ["fleabag", "gilmore-girls"], by: "Pedro Almodóvar",
  },
  {
    key: "es/el-hoyo", name: "The Platform", kind: "movie", year: 2019, countries: ES, rating: "TV-MA", minutes: 94,
    original: ["El hoyo", "es"],
    desc: "Prisoners in a vertical tower are fed by a platform that descends one floor at a time.",
    tags: ["science_fiction", "thriller", "dystopia", "horror", "surreal", "tense"],
    pop: 0.78, cities: { madrid: 0.7, "mexico-city": 0.75, "buenos-aires": 0.6, bogota: 0.6 }, fans: ["severance", "stranger-things"], by: "Galder Gaztelu-Urrutia",
  },
  {
    key: "es/abrazo-serpiente", name: "Embrace of the Serpent", kind: "movie", year: 2015, countries: CO, rating: "NR", minutes: 125,
    original: ["El abrazo de la serpiente", "es"],
    desc: "An Amazonian shaman guides two scientists, decades apart, in search of a sacred plant.",
    tags: ["drama", "adventure", "black_and_white", "slow_burn"],
    pop: 0.5, cities: { bogota: 0.8, "mexico-city": 0.4 }, fans: ["spirited-away"], by: "Ciro Guerra",
  },
  {
    key: "es/campeones", name: "Champions", kind: "movie", year: 2018, countries: ES, rating: "PG-13", minutes: 124,
    original: ["Campeones", "es"],
    desc: "A suspended basketball coach ends up training a team of players with intellectual disabilities.",
    tags: ["comedy", "drama", "sports", "warm", "upbeat"],
    pop: 0.6, cities: { madrid: 0.7, "mexico-city": 0.5 }, fans: ["ted-lasso"], by: "Javier Fesser",
  },
  {
    key: "es/no-se-aceptan-devoluciones", name: "Instructions Not Included", kind: "movie", year: 2013, countries: MX, rating: "PG-13", minutes: 115,
    original: ["No se aceptan devoluciones", "es"],
    desc: "An Acapulco playboy suddenly has to raise the baby girl left on his doorstep.",
    tags: ["comedy", "drama", "family", "warm"],
    pop: 0.65, cities: { "mexico-city": 0.8, bogota: 0.5 }, fans: ["ted-lasso", "gilmore-girls"], by: "Eugenio Derbez",
  },
  // Artists
  {
    key: "es/ed-maverick", name: "Ed Maverick", kind: "artist",
    desc: "Songwriter from Chihuahua whose quiet, sad acoustic songs took off on streaming.",
    tags: ["indie_folk", "singer_songwriter", "latin_alternative", "melancholic", "introspective"],
    pop: 0.7, cities: { "mexico-city": 0.85, bogota: 0.5, "buenos-aires": 0.4 }, fans: ["phoebe-bridgers", "mitski"],
  },
  {
    key: "es/silvana-estrada", name: "Silvana Estrada", kind: "artist",
    desc: "Veracruz singer-songwriter who plays the cuatro and writes slow, aching folk songs.",
    tags: ["indie_folk", "singer_songwriter", "latin_alternative", "bolero", "melancholic"],
    pop: 0.5, cities: { "mexico-city": 0.7, madrid: 0.4 }, fans: ["phoebe-bridgers", "mitski"],
  },
  {
    key: "es/natalia-lafourcade", name: "Natalia Lafourcade", kind: "artist",
    desc: "Mexican songwriter who mixes pop with son jarocho, bolero and Latin American folk standards.",
    tags: ["latin_pop", "latin_alternative", "singer_songwriter", "bolero", "warm"],
    pop: 0.8, cities: { "mexico-city": 0.85, madrid: 0.5, bogota: 0.6, "buenos-aires": 0.5 }, fans: ["phoebe-bridgers", "taylor-swift"],
  },
  {
    key: "es/carla-morrison", name: "Carla Morrison", kind: "artist",
    desc: "Baja California singer known for soft, heart-on-sleeve indie pop ballads.",
    tags: ["indie_pop", "latin_alternative", "singer_songwriter", "romantic", "melancholic"],
    pop: 0.65, cities: { "mexico-city": 0.8, bogota: 0.5 }, fans: ["phoebe-bridgers", "taylor-swift"],
  },
  {
    key: "es/rosalia", name: "Rosalía", kind: "artist",
    desc: "Catalan singer who blends flamenco with pop, reggaeton and electronic production.",
    tags: ["latin_pop", "flamenco", "pop", "reggaeton", "stylish"],
    pop: 0.95, cities: { madrid: 0.9, "mexico-city": 0.85, "buenos-aires": 0.8, bogota: 0.8 }, fans: ["billie-eilish", "frank-ocean"],
  },
  {
    key: "es/bomba-estereo", name: "Bomba Estéreo", kind: "artist",
    desc: "Bogotá band mixing cumbia and champeta with electronic dance music.",
    tags: ["cumbia", "electronic", "latin_alternative", "upbeat", "dance"],
    pop: 0.7, cities: { bogota: 0.9, "mexico-city": 0.7, madrid: 0.5 }, fans: ["daft-punk"],
  },
  {
    key: "es/cafe-tacvba", name: "Café Tacvba", kind: "artist",
    desc: "Mexico City-area alt-rock band that folds in son, norteño and punk.",
    tags: ["rock_en_espanol", "latin_alternative", "indie_rock", "quirky"],
    pop: 0.75, cities: { "mexico-city": 0.9, bogota: 0.6, "buenos-aires": 0.5 }, fans: ["radiohead"],
  },
  {
    key: "es/soda-stereo", name: "Soda Stereo", kind: "artist",
    desc: "Buenos Aires trio led by Gustavo Cerati, the defining Spanish-language rock band of the 1980s.",
    tags: ["rock_en_espanol", "synth_pop", "alt_rock", "nostalgic"],
    pop: 0.85, cities: { "buenos-aires": 0.95, "mexico-city": 0.75, bogota: 0.7, madrid: 0.5 }, fans: ["radiohead"],
  },
  {
    key: "es/zahara", name: "Zahara", kind: "artist",
    desc: "Andalusian singer-songwriter whose indie pop has grown darker and more electronic.",
    tags: ["spanish_indie", "indie_pop", "singer_songwriter", "introspective"],
    pop: 0.45, cities: { madrid: 0.75 }, fans: ["phoebe-bridgers", "mitski"],
  },
  {
    key: "es/vetusta-morla", name: "Vetusta Morla", kind: "artist",
    desc: "Indie rock band from the Madrid area known for big, layered anthems.",
    tags: ["spanish_indie", "indie_rock", "rock_en_espanol"],
    pop: 0.6, cities: { madrid: 0.85, "mexico-city": 0.4 }, fans: ["radiohead"],
  },
  {
    key: "es/jorge-drexler", name: "Jorge Drexler", kind: "artist",
    desc: "Uruguayan songwriter and Oscar winner known for gentle, clever, wordy songs.",
    tags: ["singer_songwriter", "latin_alternative", "warm", "witty"],
    pop: 0.6, cities: { madrid: 0.8, "buenos-aires": 0.75, "mexico-city": 0.6 }, fans: ["phoebe-bridgers"],
  },
  {
    key: "es/julieta-venegas", name: "Julieta Venegas", kind: "artist",
    desc: "Tijuana-raised songwriter and accordion player with clean, catchy pop songs.",
    tags: ["latin_pop", "singer_songwriter", "upbeat"],
    pop: 0.7, cities: { "mexico-city": 0.8, "buenos-aires": 0.7, bogota: 0.6 }, fans: ["taylor-swift"],
  },
  {
    key: "es/bad-bunny", name: "Bad Bunny", kind: "artist",
    desc: "Puerto Rican star of reggaeton and Latin trap, one of the most streamed artists anywhere.",
    tags: ["reggaeton", "latin_pop", "pop"],
    pop: 0.99, cities: { "mexico-city": 0.9, madrid: 0.85, "buenos-aires": 0.85, bogota: 0.9 }, fans: ["billie-eilish"],
  },
  {
    key: "es/natalia-lacunza", name: "Natalia Lacunza", kind: "artist",
    desc: "Navarre-born singer making soft, electronic-leaning indie pop.",
    tags: ["spanish_indie", "indie_pop", "dreamy", "melancholic"],
    pop: 0.45, cities: { madrid: 0.7 }, fans: ["phoebe-bridgers", "billie-eilish"],
  },
  // Books
  {
    key: "es/distancia-de-rescate", name: "Fever Dream", kind: "book", year: 2014,
    original: ["Distancia de rescate", "es"],
    desc: "A woman lies in a rural clinic while a boy questions her about what brought her there.",
    tags: ["literary_fiction", "latin_american_literature", "short_read", "eerie", "surreal", "slow_burn"],
    pop: 0.6, cities: { "buenos-aires": 0.7, "mexico-city": 0.6, madrid: 0.5 }, fans: ["severance", "normal-people"], by: "Samanta Schweblin",
  },
  {
    key: "es/bonsai", name: "Bonsai", kind: "book", year: 2006,
    original: ["Bonsái", "es"],
    desc: "A very short novel about two students in Santiago who fall in love partly by lying about books.",
    tags: ["literary_fiction", "latin_american_literature", "romance", "short_read", "melancholic", "introspective"],
    pop: 0.4, cities: { "buenos-aires": 0.5, "mexico-city": 0.45, madrid: 0.4 }, fans: ["normal-people"], by: "Alejandro Zambra",
  },
  {
    key: "es/cosas-que-perdimos", name: "Things We Lost in the Fire", kind: "book", year: 2016,
    original: ["Las cosas que perdimos en el fuego", "es"],
    desc: "Twelve unsettling short stories set in and around present-day Buenos Aires.",
    tags: ["short_stories", "horror", "latin_american_literature", "eerie", "dark"],
    pop: 0.55, cities: { "buenos-aires": 0.8, "mexico-city": 0.5, madrid: 0.5 }, fans: ["severance", "stranger-things"], by: "Mariana Enríquez",
  },
  {
    key: "es/agua-para-chocolate", name: "Like Water for Chocolate", kind: "book", year: 1989,
    original: ["Como agua para chocolate", "es"],
    desc: "A young cook in early 20th-century Mexico pours her forbidden love into the food she makes.",
    tags: ["magical_realism", "romance", "food", "cooking", "latin_american_literature", "family", "romantic"],
    pop: 0.8, cities: { "mexico-city": 0.8, madrid: 0.5, bogota: 0.5 }, fans: ["bake-off", "the-bear", "pride-and-prejudice", "kitchen-confidential"], by: "Laura Esquivel",
  },
  {
    key: "es/cronica-muerte", name: "Chronicle of a Death Foretold", kind: "book", year: 1981,
    original: ["Crónica de una muerte anunciada", "es"],
    desc: "A short novel that pieces together a killing the whole town knew was coming.",
    tags: ["literary_fiction", "mystery", "magical_realism", "latin_american_literature", "short_read"],
    pop: 0.85, cities: { bogota: 0.85, "mexico-city": 0.75, "buenos-aires": 0.6, madrid: 0.6 }, fans: ["orient-express", "knives-out"], by: "Gabriel García Márquez",
  },
  {
    key: "es/nada", name: "Nada", kind: "book", year: 1945,
    desc: "An 18-year-old arrives in postwar Barcelona to study and moves in with her strange, quarrelsome relatives.",
    tags: ["literary_fiction", "coming_of_age", "spanish_literature", "classic_literature", "melancholic"],
    pop: 0.5, cities: { madrid: 0.6 }, fans: ["normal-people", "pride-and-prejudice"], by: "Carmen Laforet",
  },
  {
    key: "es/un-amor", name: "A Love", kind: "book", year: 2020,
    original: ["Un amor", "es"],
    desc: "A translator moves to a remote Spanish village and is drawn into a strange arrangement with a neighbor.",
    tags: ["literary_fiction", "spanish_literature", "small_town", "slow_burn", "eerie", "introspective"],
    pop: 0.45, cities: { madrid: 0.7 }, fans: ["normal-people", "severance"], by: "Sara Mesa",
  },
  {
    key: "es/sombra-del-viento", name: "The Shadow of the Wind", kind: "book", year: 2001,
    original: ["La sombra del viento", "es"],
    desc: "A boy in 1940s Barcelona tries to learn why someone is burning every copy of a forgotten novel.",
    tags: ["mystery", "literary_fiction", "spanish_literature", "bookshop", "slow_burn"],
    pop: 0.85, cities: { madrid: 0.8, "mexico-city": 0.6, "buenos-aires": 0.55, bogota: 0.55 }, fans: ["orient-express", "harry-potter", "pride-and-prejudice"], by: "Carlos Ruiz Zafón",
  },
  {
    key: "es/aura", name: "Aura", kind: "book", year: 1962,
    desc: "A young historian takes a job in an old Mexico City house and falls under a strange spell.",
    tags: ["literary_fiction", "latin_american_literature", "short_read", "surreal", "eerie"],
    pop: 0.5, cities: { "mexico-city": 0.7, madrid: 0.3 }, fans: ["severance"], by: "Carlos Fuentes",
  },
  // Podcasts
  {
    key: "es/radio-ambulante", name: "Radio Ambulante", kind: "podcast",
    desc: "Long-form stories from across Latin America, told in Spanish by the people who lived them.",
    tags: ["storytelling", "spanish_language"],
    pop: 0.7, cities: { "mexico-city": 0.7, bogota: 0.7, "buenos-aires": 0.7, madrid: 0.5 }, fans: ["normal-people"],
  },
  {
    key: "es/hoy-hablamos", name: "Hoy Hablamos", kind: "podcast",
    desc: "Short daily episodes in clear Spanish from Spain, made for learners.",
    tags: ["language_learning", "spanish_language"],
    pop: 0.5, cities: { madrid: 0.6 },
  },
  {
    key: "es/coffee-break-spanish", name: "Coffee Break Spanish", kind: "podcast",
    desc: "Step-by-step Spanish lessons with a teacher and a learner, starting from zero.",
    tags: ["language_learning", "spanish_language"],
    pop: 0.65,
  },
  {
    key: "es/espanolistos", name: "Españolistos", kind: "podcast",
    desc: "Relaxed conversations in Spanish about everyday topics, aimed at intermediate learners.",
    tags: ["language_learning", "spanish_language", "podcast_comedy"],
    pop: 0.5, cities: { bogota: 0.5 },
  },
  {
    key: "es/nadie-sabe-nada", name: "Nadie Sabe Nada", kind: "podcast",
    desc: "Two comedians improvise answers to listeners' questions on Spanish radio.",
    tags: ["podcast_comedy", "spanish_language"],
    pop: 0.6, cities: { madrid: 0.85 }, fans: ["fleabag", "the-office"],
  },
  {
    key: "es/leyendas-legendarias", name: "Leyendas Legendarias", kind: "podcast",
    desc: "A Mexican comedy podcast about legends, mysteries and true crime cases.",
    tags: ["podcast_comedy", "true_crime", "spanish_language"],
    pop: 0.75, cities: { "mexico-city": 0.85, bogota: 0.5 }, fans: ["knives-out", "stranger-things"],
  },
  // Restaurants (Chicago)
  {
    key: "es/frontera-grill", name: "Frontera Grill", kind: "place", city: "Chicago", address: "River North, Chicago",
    desc: "Rick Bayless's long-running restaurant for regional Mexican cooking.",
    tags: ["mexican"], pop: 0.85, fans: ["the-bear", "kitchen-confidential"],
  },
  {
    key: "es/topolobampo", name: "Topolobampo", kind: "place", city: "Chicago", address: "River North, Chicago",
    desc: "Fine-dining sibling of Frontera Grill with Mexican tasting menus.",
    tags: ["mexican"], pop: 0.7, fans: ["the-bear", "succession"],
  },
  {
    key: "es/carnitas-uruapan", name: "Carnitas Uruapan", kind: "place", city: "Chicago", address: "Pilsen, Chicago",
    desc: "Pilsen counter famous for Michoacán-style carnitas sold by the pound.",
    tags: ["mexican", "tacos"], pop: 0.65, fans: ["the-bear"],
  },
  {
    key: "es/mi-tocaya", name: "Mi Tocaya Antojería", kind: "place", city: "Chicago", address: "Logan Square, Chicago",
    desc: "Logan Square spot for Mexican antojitos, the small dishes and snacks.",
    tags: ["mexican"], pop: 0.55, fans: ["the-bear", "fleabag"],
  },
  {
    key: "es/cafe-ba-ba-reeba", name: "Café Ba-Ba-Reeba!", kind: "place", city: "Chicago", address: "Lincoln Park, Chicago",
    desc: "Lincoln Park tapas bar serving small Spanish plates and paella.",
    tags: ["spanish", "tapas"], pop: 0.6, fans: ["gilmore-girls"],
  },
  {
    key: "es/tango-sur", name: "Tango Sur", kind: "place", city: "Chicago", address: "Lakeview, Chicago",
    desc: "Lakeview Argentine steakhouse known for grilled meats and empanadas.",
    tags: ["argentinian"], pop: 0.5,
  },
];
