import type { CatalogItem } from "./types";

const FR = ["France"];

export const FRENCH: CatalogItem[] = [
  // Series
  {
    key: "fr/dix-pour-cent", name: "Call My Agent!", kind: "tv_show", year: 2015, finale: 2020, countries: FR, rating: "TV-14", minutes: 52,
    original: ["Dix pour cent", "fr"],
    desc: "Agents at a Paris talent agency scramble to keep their famous clients happy.",
    local: ["série française sur une agence d'acteurs parisienne", "fr"],
    tags: ["comedy", "drama", "workplace", "showbiz", "city_life", "witty"],
    pop: 0.8, cities: { paris: 0.9, montreal: 0.6 }, fans: ["succession", "fleabag", "the-office", "the-bear"],
  },
  {
    key: "fr/lupin", name: "Lupin", kind: "tv_show", year: 2021, countries: FR, rating: "TV-MA", minutes: 45,
    desc: "A gentleman thief inspired by Arsène Lupin sets out to clear his father's name in Paris.",
    tags: ["thriller", "heist", "mystery", "crime", "stylish"],
    pop: 0.9, cities: { paris: 0.9, montreal: 0.7 }, fans: ["knives-out", "orient-express", "breaking-bad"],
  },
  {
    key: "fr/hpi", name: "HPI", kind: "tv_show", year: 2021, countries: FR, rating: "TV-14", minutes: 52,
    original: ["HPI : Haut Potentiel Intellectuel", "fr"],
    desc: "A cleaner with a sky-high IQ becomes a consultant for the police in Lille.",
    tags: ["comedy", "crime", "procedural", "mystery", "whodunit", "witty", "quirky"],
    pop: 0.7, cities: { paris: 0.85, montreal: 0.5 }, fans: ["knives-out", "orient-express", "fleabag"],
  },
  {
    key: "fr/les-revenants", name: "The Returned", kind: "tv_show", year: 2012, finale: 2015, countries: FR, rating: "TV-MA", minutes: 52,
    original: ["Les Revenants", "fr"],
    desc: "In an Alpine town, people who died years ago walk back home as if nothing happened.",
    tags: ["drama", "mystery", "fantasy", "small_town", "eerie", "slow_burn"],
    pop: 0.6, cities: { paris: 0.6, montreal: 0.5 }, fans: ["severance", "stranger-things"],
  },
  {
    key: "fr/engrenages", name: "Spiral", kind: "tv_show", year: 2005, finale: 2020, countries: FR, rating: "TV-MA", minutes: 52,
    original: ["Engrenages", "fr"],
    desc: "Paris police, prosecutors and lawyers work cases through a messy justice system.",
    tags: ["crime", "procedural", "drama", "tense"],
    pop: 0.55, cities: { paris: 0.7 }, fans: ["breaking-bad", "succession"],
  },
  {
    key: "fr/astrid", name: "Astrid", kind: "tv_show", year: 2019, countries: FR, rating: "TV-14", minutes: 52,
    original: ["Astrid et Raphaëlle", "fr"],
    desc: "A police commander teams up with an autistic archivist from the criminal records office.",
    tags: ["crime", "procedural", "mystery", "whodunit", "workplace"],
    pop: 0.5, cities: { paris: 0.7, montreal: 0.45 }, fans: ["orient-express", "knives-out"],
  },
  {
    key: "fr/bazar-de-la-charite", name: "The Bonfire of Destiny", kind: "tv_show", year: 2019, countries: FR, rating: "TV-14", minutes: 52,
    original: ["Le Bazar de la Charité", "fr"],
    desc: "Three women's lives change after the deadly 1897 fire at a Paris charity bazaar.",
    tags: ["period_drama", "drama", "romance"],
    pop: 0.55, cities: { paris: 0.6, montreal: 0.45 }, fans: ["pride-and-prejudice"],
  },
  {
    key: "fr/meurtres-a", name: "Murder In...", kind: "tv_show", year: 2013, countries: FR, rating: "TV-14", minutes: 90,
    original: ["Meurtres à...", "fr"],
    desc: "Each feature-length episode solves a murder in a different French town.",
    tags: ["mystery", "whodunit", "crime", "small_town"],
    pop: 0.45, cities: { paris: 0.55 }, fans: ["orient-express", "knives-out"],
  },
  {
    key: "fr/mytho", name: "Mythomaniac", kind: "tv_show", year: 2019, finale: 2021, countries: FR, rating: "TV-MA", minutes: 50,
    original: ["Mytho", "fr"],
    desc: "An overlooked mother pretends to be ill to win back her family's attention, and the lie grows.",
    tags: ["dark_comedy", "drama", "family", "satire"],
    pop: 0.45, cities: { paris: 0.6 }, fans: ["fleabag", "succession"],
  },
  {
    key: "fr/hippocrate", name: "Hippocrate", kind: "tv_show", year: 2018, countries: FR, rating: "TV-MA", minutes: 52,
    desc: "Young doctors are left running a hospital's internal medicine ward on their own.",
    tags: ["drama", "hospital", "workplace", "tense"],
    pop: 0.45, cities: { paris: 0.6 }, fans: ["the-bear"],
  },
  // Films
  {
    key: "fr/anatomie", name: "Anatomy of a Fall", kind: "movie", year: 2023, countries: FR, rating: "R", minutes: 152,
    original: ["Anatomie d'une chute", "fr"],
    desc: "A novelist stands trial after her husband falls to his death outside their chalet.",
    tags: ["drama", "mystery", "courtroom", "tense", "slow_burn"],
    pop: 0.8, cities: { paris: 0.85, montreal: 0.7 }, fans: ["knives-out", "succession", "orient-express"], by: "Justine Triet",
  },
  {
    key: "fr/8-femmes", name: "8 Women", kind: "movie", year: 2002, countries: FR, rating: "R", minutes: 111,
    original: ["8 femmes", "fr"],
    desc: "Eight women snowed in at a country house sing, bicker and accuse each other of a murder.",
    tags: ["mystery", "whodunit", "comedy", "musical", "stylish", "witty"],
    pop: 0.6, cities: { paris: 0.6 }, fans: ["knives-out", "orient-express"], by: "François Ozon",
  },
  {
    key: "fr/amelie", name: "Amélie", kind: "movie", year: 2001, countries: FR, rating: "R", minutes: 122,
    original: ["Le Fabuleux Destin d'Amélie Poulain", "fr"],
    desc: "A shy Montmartre café waitress secretly arranges small acts of happiness for strangers.",
    tags: ["romantic_comedy", "comedy", "city_life", "whimsical", "quirky"],
    pop: 0.92, cities: { paris: 0.9, montreal: 0.8 }, fans: ["gilmore-girls", "spirited-away"], by: "Jean-Pierre Jeunet",
  },
  {
    key: "fr/diner-de-cons", name: "The Dinner Game", kind: "movie", year: 1998, countries: FR, rating: "PG-13", minutes: 80,
    original: ["Le Dîner de cons", "fr"],
    desc: "A Paris publisher's cruel dinner-party joke backfires when his guest wrecks his whole evening.",
    tags: ["comedy", "satire", "witty"],
    pop: 0.7, cities: { paris: 0.8, montreal: 0.7 }, fans: ["the-office", "fleabag"], by: "Francis Veber",
  },
  {
    key: "fr/intouchables", name: "The Intouchables", kind: "movie", year: 2011, countries: FR, rating: "R", minutes: 112,
    original: ["Intouchables", "fr"],
    desc: "A wealthy quadriplegic hires a young man from the suburbs as his live-in carer.",
    tags: ["comedy", "drama", "friendship", "warm"],
    pop: 0.9, cities: { paris: 0.85, montreal: 0.8 }, fans: ["ted-lasso"],
  },
  {
    key: "fr/taste-of-things", name: "The Taste of Things", kind: "movie", year: 2023, countries: FR, rating: "PG-13", minutes: 135,
    original: ["La Passion de Dodin Bouffant", "fr"],
    desc: "A celebrated gourmet and his longtime cook make elaborate meals in 1880s France.",
    tags: ["drama", "food", "cooking", "romance", "period_drama", "slow_burn"],
    pop: 0.6, cities: { paris: 0.7, montreal: 0.5 }, fans: ["the-bear", "bake-off", "kitchen-confidential"], by: "Trần Anh Hùng",
  },
  {
    key: "fr/portrait", name: "Portrait of a Lady on Fire", kind: "movie", year: 2019, countries: FR, rating: "R", minutes: 122,
    original: ["Portrait de la jeune fille en feu", "fr"],
    desc: "An 18th-century painter is hired to paint a young woman's wedding portrait without her knowing.",
    tags: ["romance", "period_drama", "drama", "art", "slow_burn"],
    pop: 0.75, cities: { paris: 0.7, montreal: 0.6 }, fans: ["pride-and-prejudice", "normal-people"], by: "Céline Sciamma",
  },
  {
    key: "fr/choristes", name: "The Chorus", kind: "movie", year: 2004, countries: FR, rating: "PG-13", minutes: 97,
    original: ["Les Choristes", "fr"],
    desc: "A kind music teacher forms a choir at a strict boarding school for boys in 1949.",
    tags: ["drama", "music", "school", "warm"],
    pop: 0.75, cities: { paris: 0.7, montreal: 0.6 }, fans: ["ted-lasso"],
  },
  // Artists
  {
    key: "fr/stromae", name: "Stromae", kind: "artist",
    desc: "Belgian singer and producer behind 'Alors on danse' and 'Papaoutai', dance songs with sad lyrics.",
    tags: ["french_pop", "electronic", "dance", "melancholic", "stylish"],
    pop: 0.9, cities: { paris: 0.9, montreal: 0.85 }, fans: ["daft-punk", "frank-ocean"],
  },
  {
    key: "fr/angele", name: "Angèle", kind: "artist",
    desc: "Brussels singer known for bright, witty French pop like 'Tout oublier'.",
    tags: ["french_pop", "pop", "upbeat", "witty"],
    pop: 0.85, cities: { paris: 0.85, montreal: 0.7 }, fans: ["taylor-swift", "billie-eilish"],
  },
  {
    key: "fr/limperatrice", name: "L'Impératrice", kind: "artist",
    desc: "Paris band playing glossy disco-pop sung in French over a tight rhythm section.",
    tags: ["french_pop", "disco", "dance", "stylish", "upbeat"],
    pop: 0.6, cities: { paris: 0.75, montreal: 0.6 }, fans: ["daft-punk"],
  },
  {
    key: "fr/polo-and-pan", name: "Polo & Pan", kind: "artist",
    desc: "Paris duo making sunny electronic pop with French vocals and samples.",
    tags: ["electronic", "french_pop", "dance", "dreamy"],
    pop: 0.6, cities: { paris: 0.7, montreal: 0.6 }, fans: ["daft-punk"],
  },
  {
    key: "fr/clara-luciani", name: "Clara Luciani", kind: "artist",
    desc: "Singer with a deep voice and retro pop hits like 'La grenade' and 'Le reste'.",
    tags: ["french_pop", "chanson", "disco", "stylish"],
    pop: 0.7, cities: { paris: 0.8, montreal: 0.6 }, fans: ["taylor-swift", "daft-punk"],
  },
  {
    key: "fr/juliette-armanet", name: "Juliette Armanet", kind: "artist",
    desc: "Pianist and singer bringing back big, romantic 1970s French pop.",
    tags: ["french_pop", "chanson", "disco", "romantic"],
    pop: 0.55, cities: { paris: 0.75 }, fans: ["taylor-swift"],
  },
  {
    key: "fr/christine-and-the-queens", name: "Christine and the Queens", kind: "artist",
    desc: "French act known for sleek, dramatic synth-pop sung in French and English.",
    tags: ["french_pop", "synth_pop", "electronic", "stylish"],
    pop: 0.7, cities: { paris: 0.8, montreal: 0.65 }, fans: ["billie-eilish", "daft-punk"],
  },
  {
    key: "fr/francoise-hardy", name: "Françoise Hardy", kind: "artist",
    desc: "Singer of 1960s yé-yé and wistful French pop, from 'Tous les garçons et les filles' on.",
    tags: ["chanson", "french_pop", "melancholic", "nostalgic"],
    pop: 0.75, cities: { paris: 0.7, montreal: 0.6 }, fans: ["phoebe-bridgers"],
  },
  {
    key: "fr/zaho-de-sagazan", name: "Zaho de Sagazan", kind: "artist",
    desc: "Singer from Saint-Nazaire whose piano-and-synth songs are dark, intense and very French.",
    tags: ["chanson", "electronic", "synth_pop", "melancholic"],
    pop: 0.55, cities: { paris: 0.75, montreal: 0.5 }, fans: ["phoebe-bridgers", "billie-eilish"],
  },
  {
    key: "fr/vianney", name: "Vianney", kind: "artist",
    desc: "Guitar-and-voice songwriter with simple, catchy French songs.",
    tags: ["french_pop", "singer_songwriter", "warm", "gentle"],
    pop: 0.55, cities: { paris: 0.7, montreal: 0.5 }, fans: ["taylor-swift", "phoebe-bridgers"],
  },
  // Books
  {
    key: "fr/petit-prince", name: "The Little Prince", kind: "book", year: 1943,
    original: ["Le Petit Prince", "fr"],
    desc: "A pilot stranded in the desert meets a small prince who has travelled from his tiny planet.",
    tags: ["fable", "classic_literature", "french_literature", "short_read", "whimsical", "gentle"],
    pop: 0.95, cities: { paris: 0.8, montreal: 0.8 }, fans: ["spirited-away", "harry-potter"], by: "Antoine de Saint-Exupéry",
  },
  {
    key: "fr/nympheas-noirs", name: "Black Water Lilies", kind: "book", year: 2011,
    original: ["Nymphéas noirs", "fr"],
    desc: "A murder in Monet's village of Giverny ties together three women of very different ages.",
    tags: ["mystery", "detective_fiction", "whodunit", "french_literature"],
    pop: 0.6, cities: { paris: 0.7 }, fans: ["orient-express", "knives-out"], by: "Michel Bussi",
  },
  {
    key: "fr/pietr-le-letton", name: "Pietr the Latvian", kind: "book", year: 1931,
    original: ["Pietr-le-Letton", "fr"],
    desc: "Inspector Maigret's first case: a con man who seems to be in two places at once.",
    tags: ["detective_fiction", "mystery", "crime", "classic_literature", "short_read", "french_literature"],
    pop: 0.6, cities: { paris: 0.6 }, fans: ["orient-express"], by: "Georges Simenon",
  },
  {
    key: "fr/cercles-bleus", name: "The Chalk Circle Man", kind: "book", year: 1991,
    original: ["L'Homme aux cercles bleus", "fr"],
    desc: "Someone draws blue chalk circles around objects on Paris pavements, until a body turns up inside one.",
    tags: ["detective_fiction", "mystery", "french_literature", "quirky"],
    pop: 0.5, cities: { paris: 0.6 }, fans: ["orient-express", "knives-out"], by: "Fred Vargas",
  },
  {
    key: "fr/herisson", name: "The Elegance of the Hedgehog", kind: "book", year: 2006,
    original: ["L'Élégance du hérisson", "fr"],
    desc: "A secretly brilliant concierge and a precocious girl in a Paris apartment building find each other.",
    tags: ["literary_fiction", "french_literature", "city_life", "witty", "introspective"],
    pop: 0.7, cities: { paris: 0.7, montreal: 0.6 }, fans: ["pride-and-prejudice", "normal-people", "gilmore-girls"], by: "Muriel Barbery",
  },
  {
    key: "fr/harry-quebert", name: "The Truth About the Harry Quebert Affair", kind: "book", year: 2012,
    original: ["La Vérité sur l'affaire Harry Quebert", "fr"],
    desc: "A young novelist investigates his mentor, accused of a murder in a small New Hampshire town.",
    tags: ["mystery", "thriller", "whodunit", "small_town", "french_literature"],
    pop: 0.75, cities: { paris: 0.75, montreal: 0.6 }, fans: ["knives-out", "orient-express"], by: "Joël Dicker",
  },
  {
    key: "fr/bonjour-tristesse", name: "Bonjour Tristesse", kind: "book", year: 1954,
    original: ["Bonjour tristesse", "fr"],
    desc: "A 17-year-old on a Riviera summer holiday schemes to break up her father's new romance.",
    tags: ["literary_fiction", "coming_of_age", "short_read", "classic_literature", "french_literature", "melancholic"],
    pop: 0.7, cities: { paris: 0.6, montreal: 0.5 }, fans: ["normal-people", "pride-and-prejudice"], by: "Françoise Sagan",
  },
  // Podcasts
  {
    key: "fr/innerfrench", name: "InnerFrench", kind: "podcast",
    desc: "Interesting topics explained in clear, slow French for intermediate learners.",
    tags: ["language_learning", "french_language"],
    pop: 0.65,
  },
  {
    key: "fr/coffee-break-french", name: "Coffee Break French", kind: "podcast",
    desc: "Structured French lessons, one coffee break at a time.",
    tags: ["language_learning", "french_language"],
    pop: 0.6,
  },
  {
    key: "fr/transfert", name: "Transfert", kind: "podcast",
    desc: "People tell true stories from their own lives, in French.",
    tags: ["storytelling", "french_language"],
    pop: 0.5, cities: { paris: 0.6, montreal: 0.4 }, fans: ["normal-people", "fleabag"],
  },
  {
    key: "fr/pieds-sur-terre", name: "Les Pieds sur terre", kind: "podcast",
    desc: "Short documentary stories in people's own voices, from France Culture.",
    tags: ["storytelling", "french_language"],
    pop: 0.5, cities: { paris: 0.6 },
  },
  {
    key: "fr/easy-french", name: "Easy French", kind: "podcast",
    desc: "Street interviews and relaxed conversations in everyday French.",
    tags: ["language_learning", "french_language"],
    pop: 0.5,
  },
  // Restaurants (New York)
  {
    key: "fr/balthazar", name: "Balthazar", kind: "place", city: "New York", address: "SoHo, New York",
    desc: "Busy SoHo brasserie with a bakery next door.",
    tags: ["french", "brasserie"], pop: 0.85, fans: ["succession", "gilmore-girls"],
  },
  {
    key: "fr/le-coucou", name: "Le Coucou", kind: "place", city: "New York", address: "SoHo, New York",
    desc: "Formal French dining room with classic sauces and a grand space.",
    tags: ["french"], pop: 0.7, fans: ["succession", "the-bear"],
  },
  {
    key: "fr/raouls", name: "Raoul's", kind: "place", city: "New York", address: "SoHo, New York",
    desc: "Long-running SoHo bistro known for its steak au poivre.",
    tags: ["french", "bistro"], pop: 0.65, fans: ["the-bear", "knives-out"],
  },
  {
    key: "fr/pastis", name: "Pastis", kind: "place", city: "New York", address: "Meatpacking District, New York",
    desc: "Big, bright Paris-style brasserie in the Meatpacking District.",
    tags: ["french", "brasserie"], pop: 0.7, fans: ["succession"],
  },
  {
    key: "fr/buvette", name: "Buvette", kind: "place", city: "New York", address: "West Village, New York",
    desc: "Tiny West Village café and wine bar serving small French plates all day.",
    tags: ["french", "bistro"], pop: 0.6, fans: ["gilmore-girls", "bake-off"],
  },
];
