import type { CatalogItem } from "./types";

const JP = ["Japan"];

export const JAPANESE: CatalogItem[] = [
  // Series
  {
    key: "ja/midnight-diner", name: "Midnight Diner: Tokyo Stories", kind: "tv_show", year: 2016, finale: 2019, countries: JP, rating: "TV-14", minutes: 25,
    original: ["深夜食堂", "ja"],
    desc: "A late-night Tokyo diner cooks whatever regulars ask for, and each episode follows one customer.",
    local: ["東京の深夜営業の食堂を舞台にしたドラマ", "ja"],
    tags: ["drama", "food", "cooking", "slice_of_life", "city_life", "warm", "gentle"],
    pop: 0.65, cities: { tokyo: 0.75, osaka: 0.6 }, fans: ["the-bear", "kitchen-confidential", "bake-off"],
  },
  {
    key: "ja/makanai", name: "The Makanai: Cooking for the Maiko House", kind: "tv_show", year: 2023, countries: JP, rating: "TV-PG", minutes: 45,
    original: ["舞妓さんちのまかないさん", "ja"],
    desc: "A teenager from Aomori becomes the live-in cook for a house of apprentice geiko in Kyoto.",
    tags: ["drama", "food", "cooking", "slice_of_life", "friendship", "gentle", "warm"],
    pop: 0.55, cities: { tokyo: 0.5, osaka: 0.65 }, fans: ["the-bear", "bake-off", "gilmore-girls"], by: "Hirokazu Kore-eda",
  },
  {
    key: "ja/solitary-gourmet", name: "Solitary Gourmet", kind: "tv_show", year: 2012, countries: JP, rating: "TV-G", minutes: 24,
    original: ["孤独のグルメ", "ja"],
    desc: "A solo importer visits clients around Tokyo and eats a quiet, perfect meal alone after each job.",
    tags: ["slice_of_life", "food", "comedy", "city_life", "gentle"],
    pop: 0.6, cities: { tokyo: 0.8, osaka: 0.55 }, fans: ["the-bear", "kitchen-confidential"],
  },
  {
    key: "ja/first-love", name: "First Love", kind: "tv_show", year: 2022, countries: JP, rating: "TV-14", minutes: 55,
    original: ["初恋", "ja"],
    desc: "Two first loves from Hokkaido drift apart and back over twenty years, set to Hikaru Utada's songs.",
    tags: ["romance", "drama", "nostalgia", "music", "melancholic", "nostalgic"],
    pop: 0.65, cities: { tokyo: 0.7, osaka: 0.6 }, fans: ["normal-people", "frank-ocean", "taylor-swift"],
  },
  {
    key: "ja/alice-in-borderland", name: "Alice in Borderland", kind: "tv_show", year: 2020, finale: 2025, countries: JP, rating: "TV-MA", minutes: 50,
    original: ["今際の国のアリス", "ja"],
    desc: "Gamers stranded in an empty Tokyo must win deadly games to stay alive.",
    tags: ["thriller", "science_fiction", "dystopia", "survival", "tense"],
    pop: 0.85, cities: { tokyo: 0.8, osaka: 0.7 }, fans: ["severance", "stranger-things"],
  },
  {
    key: "ja/delicious-in-dungeon", name: "Delicious in Dungeon", kind: "tv_show", year: 2024, countries: JP, rating: "TV-14", minutes: 24,
    original: ["ダンジョン飯", "ja"],
    desc: "Adventurers deep in a dungeon survive by cooking the monsters they fight.",
    tags: ["anime", "animation", "fantasy", "cooking", "food", "comedy", "quirky"],
    pop: 0.7, cities: { tokyo: 0.7, osaka: 0.65 }, fans: ["the-bear", "spirited-away", "bake-off", "arcane"],
  },
  {
    key: "ja/laid-back-camp", name: "Laid-Back Camp", kind: "tv_show", year: 2018, countries: JP, rating: "TV-G", minutes: 24,
    original: ["ゆるキャン△", "ja"],
    desc: "High school girls go winter camping near Mount Fuji, cook outdoors and take it easy.",
    tags: ["anime", "animation", "slice_of_life", "friendship", "cozy", "gentle"],
    pop: 0.6, cities: { tokyo: 0.6, osaka: 0.55 }, fans: ["bake-off", "gilmore-girls"],
  },
  {
    key: "ja/shirobako", name: "Shirobako", kind: "tv_show", year: 2014, countries: JP, rating: "TV-14", minutes: 24,
    desc: "Five friends chase their dream jobs at a Tokyo animation studio running on tight deadlines.",
    tags: ["anime", "animation", "workplace", "comedy", "drama", "friendship"],
    pop: 0.5, cities: { tokyo: 0.6 }, fans: ["the-bear", "the-office", "severance"],
  },
  {
    key: "ja/samurai-gourmet", name: "Samurai Gourmet", kind: "tv_show", year: 2017, countries: JP, rating: "TV-PG", minutes: 25,
    original: ["野武士のグルメ", "ja"],
    desc: "A newly retired office worker finds his nerve at mealtimes by imagining a wandering samurai.",
    tags: ["comedy", "food", "slice_of_life", "whimsical", "gentle"],
    pop: 0.45, cities: { tokyo: 0.6 }, fans: ["the-bear", "kitchen-confidential"],
  },
  {
    key: "ja/kantaro", name: "Kantaro: The Sweet Tooth Salaryman", kind: "tv_show", year: 2017, countries: JP, rating: "TV-PG", minutes: 25,
    original: ["さぼリーマン甘太朗", "ja"],
    desc: "An efficient salesman sneaks out of work to visit Tokyo's best dessert shops.",
    tags: ["comedy", "food", "baking", "workplace", "quirky"],
    pop: 0.4, cities: { tokyo: 0.6 }, fans: ["bake-off", "the-office"],
  },
  {
    key: "ja/hanzawa-naoki", name: "Hanzawa Naoki", kind: "tv_show", year: 2013, finale: 2020, countries: JP, rating: "TV-14", minutes: 50,
    original: ["半沢直樹", "ja"],
    desc: "A bank loan officer fights back against the superiors who blame him for a failed loan.",
    tags: ["drama", "workplace", "power_struggle", "tense"],
    pop: 0.7, cities: { tokyo: 0.85, osaka: 0.8 }, fans: ["succession"],
  },
  // Films
  {
    key: "ja/tampopo", name: "Tampopo", kind: "movie", year: 1985, countries: JP, rating: "NR", minutes: 114,
    original: ["タンポポ", "ja"],
    desc: "A truck driver helps a widow turn her struggling roadside shop into a great ramen restaurant.",
    tags: ["comedy", "food", "cooking", "quirky", "warm"],
    pop: 0.6, cities: { tokyo: 0.6 }, fans: ["the-bear", "kitchen-confidential", "bake-off"], by: "Juzo Itami",
  },
  {
    key: "ja/sweet-bean", name: "Sweet Bean", kind: "movie", year: 2015, countries: JP, rating: "NR", minutes: 113,
    original: ["あん", "ja"],
    desc: "An elderly woman teaches a dorayaki seller to make sweet bean paste from scratch.",
    tags: ["drama", "food", "baking", "gentle", "melancholic", "slow_burn"],
    pop: 0.5, cities: { tokyo: 0.5 }, fans: ["bake-off", "the-bear"], by: "Naomi Kawase",
  },
  {
    key: "ja/shoplifters", name: "Shoplifters", kind: "movie", year: 2018, countries: JP, rating: "R", minutes: 121,
    original: ["万引き家族", "ja"],
    desc: "A makeshift family in Tokyo gets by on small thefts until a girl they take in changes everything.",
    tags: ["drama", "family", "found_family", "melancholic", "slow_burn"],
    pop: 0.75, cities: { tokyo: 0.7, osaka: 0.6 }, fans: ["normal-people", "fleabag"], by: "Hirokazu Kore-eda",
  },
  {
    key: "ja/perfect-days", name: "Perfect Days", kind: "movie", year: 2023, countries: ["Japan", "Germany"], rating: "PG", minutes: 124,
    desc: "A Tokyo public-toilet cleaner keeps a quiet routine of work, paperbacks, cassettes and trees.",
    tags: ["drama", "slow_burn", "city_life", "music", "gentle", "introspective"],
    pop: 0.7, cities: { tokyo: 0.75 }, fans: ["frank-ocean", "the-bear", "normal-people"], by: "Wim Wenders",
  },
  {
    key: "ja/your-name", name: "Your Name.", kind: "movie", year: 2016, countries: JP, rating: "PG", minutes: 106,
    original: ["君の名は。", "ja"],
    desc: "A Tokyo boy and a country girl start waking up in each other's bodies.",
    tags: ["anime", "animation", "romance", "fantasy", "coming_of_age", "dreamy"],
    pop: 0.9, cities: { tokyo: 0.9, osaka: 0.85 }, fans: ["spirited-away", "normal-people", "taylor-swift"], by: "Makoto Shinkai",
  },
  {
    key: "ja/totoro", name: "My Neighbor Totoro", kind: "movie", year: 1988, countries: JP, rating: "G", minutes: 86,
    original: ["となりのトトロ", "ja"],
    desc: "Two sisters in the countryside befriend a giant forest spirit.",
    tags: ["anime", "animation", "fantasy", "family", "whimsical", "cozy"],
    pop: 0.9, cities: { tokyo: 0.75, osaka: 0.75 }, fans: ["spirited-away", "bake-off"], by: "Hayao Miyazaki",
  },
  {
    key: "ja/drive-my-car", name: "Drive My Car", kind: "movie", year: 2021, countries: JP, rating: "NR", minutes: 179,
    original: ["ドライブ・マイ・カー", "ja"],
    desc: "A widowed stage director forms a quiet bond with the young woman hired to drive his car.",
    tags: ["drama", "grief", "slow_burn", "introspective"],
    pop: 0.65, cities: { tokyo: 0.6 }, fans: ["normal-people", "fleabag"], by: "Ryusuke Hamaguchi",
  },
  {
    key: "ja/kiki", name: "Kiki's Delivery Service", kind: "movie", year: 1989, countries: JP, rating: "G", minutes: 103,
    original: ["魔女の宅急便", "ja"],
    desc: "A 13-year-old witch moves to a seaside town, lodges at a bakery and starts a flying delivery service.",
    tags: ["anime", "animation", "fantasy", "coming_of_age", "baking", "cozy"],
    pop: 0.85, cities: { tokyo: 0.7, osaka: 0.7 }, fans: ["spirited-away", "bake-off", "gilmore-girls"], by: "Hayao Miyazaki",
  },
  // Artists
  {
    key: "ja/fujii-kaze", name: "Fujii Kaze", kind: "artist",
    original: ["藤井 風", "ja"],
    desc: "Okayama-born singer and pianist who mixes J-pop, soul and R&B.",
    tags: ["j_pop", "rnb", "singer_songwriter", "dreamy"],
    pop: 0.8, cities: { tokyo: 0.85, osaka: 0.8 }, fans: ["frank-ocean"],
  },
  {
    key: "ja/hikaru-utada", name: "Hikaru Utada", kind: "artist",
    original: ["宇多田ヒカル", "ja"],
    desc: "Singer-songwriter who has shaped Japanese pop and R&B since 1998.",
    tags: ["j_pop", "rnb", "singer_songwriter", "melancholic", "introspective"],
    pop: 0.85, cities: { tokyo: 0.9, osaka: 0.85 }, fans: ["frank-ocean", "taylor-swift"],
  },
  {
    key: "ja/mariya-takeuchi", name: "Mariya Takeuchi", kind: "artist",
    original: ["竹内まりや", "ja"],
    desc: "City pop singer whose 1984 song 'Plastic Love' found a huge new audience online.",
    tags: ["city_pop", "j_pop", "nostalgic", "stylish"],
    pop: 0.7, cities: { tokyo: 0.7, osaka: 0.65 }, fans: ["daft-punk", "frank-ocean"],
  },
  {
    key: "ja/tatsuro-yamashita", name: "Tatsuro Yamashita", kind: "artist",
    original: ["山下達郎", "ja"],
    desc: "Producer and singer behind sunny, intricate 1980s city pop records.",
    tags: ["city_pop", "j_pop", "upbeat", "nostalgic"],
    pop: 0.65, cities: { tokyo: 0.75, osaka: 0.7 }, fans: ["daft-punk"],
  },
  {
    key: "ja/kenshi-yonezu", name: "Kenshi Yonezu", kind: "artist",
    original: ["米津玄師", "ja"],
    desc: "Songwriter behind 'Lemon' and 'Kick Back', one of Japan's most streamed artists.",
    tags: ["j_pop", "j_rock", "singer_songwriter", "anime_soundtrack", "melancholic"],
    pop: 0.9, cities: { tokyo: 0.9, osaka: 0.9 }, fans: ["billie-eilish", "phoebe-bridgers"],
  },
  {
    key: "ja/aimyon", name: "Aimyon", kind: "artist",
    original: ["あいみょん", "ja"],
    desc: "Hyōgo-born singer-songwriter with a guitar, a husky voice and catchy, heartbroken songs.",
    tags: ["j_pop", "singer_songwriter", "indie_folk", "melancholic"],
    pop: 0.7, cities: { tokyo: 0.8, osaka: 0.85 }, fans: ["phoebe-bridgers", "taylor-swift"],
  },
  {
    key: "ja/lamp", name: "Lamp", kind: "artist",
    original: ["ランプ", "ja"],
    desc: "Tokyo trio making soft pop with a bossa nova feel, a favorite on late-night playlists.",
    tags: ["city_pop", "indie_pop", "dreamy", "gentle"],
    pop: 0.45, cities: { tokyo: 0.5 }, fans: ["frank-ocean", "phoebe-bridgers"],
  },
  {
    key: "ja/yoasobi", name: "YOASOBI", kind: "artist",
    desc: "Duo that turns short stories into fast, bright pop songs like 'Idol' and 'Yoru ni Kakeru'.",
    tags: ["j_pop", "anime_soundtrack", "electronic", "upbeat"],
    pop: 0.9, cities: { tokyo: 0.9, osaka: 0.9 }, fans: ["taylor-swift", "billie-eilish"],
  },
  {
    key: "ja/vaundy", name: "Vaundy", kind: "artist",
    desc: "Tokyo multi-instrumentalist who writes, produces and designs almost everything himself.",
    tags: ["j_pop", "j_rock", "alt_pop"],
    pop: 0.7, cities: { tokyo: 0.8, osaka: 0.75 }, fans: ["frank-ocean", "billie-eilish"],
  },
  {
    key: "ja/haruomi-hosono", name: "Haruomi Hosono", kind: "artist",
    original: ["細野晴臣", "ja"],
    desc: "Founding member of Yellow Magic Orchestra and a quiet giant of Japanese pop and folk.",
    tags: ["city_pop", "electronic", "ambient", "nostalgic"],
    pop: 0.5, cities: { tokyo: 0.6 }, fans: ["daft-punk", "radiohead"],
  },
  {
    key: "ja/king-gnu", name: "King Gnu", kind: "artist",
    desc: "Tokyo band mixing rock, jazz and orchestral pop into big, dramatic songs.",
    tags: ["j_rock", "alt_pop"],
    pop: 0.7, cities: { tokyo: 0.8, osaka: 0.75 }, fans: ["radiohead"],
  },
  // Books
  {
    key: "ja/kitchen", name: "Kitchen", kind: "book", year: 1988,
    original: ["キッチン", "ja"],
    desc: "After her grandmother dies, a young woman who feels safest in kitchens moves in with a friend and his mother.",
    tags: ["literary_fiction", "japanese_literature", "grief", "food", "kitchen", "short_read", "gentle", "melancholic"],
    pop: 0.65, cities: { tokyo: 0.6 }, fans: ["kitchen-confidential", "normal-people", "the-bear"], by: "Banana Yoshimoto",
  },
  {
    key: "ja/convenience-store-woman", name: "Convenience Store Woman", kind: "book", year: 2016,
    original: ["コンビニ人間", "ja"],
    desc: "A 36-year-old who has worked at the same convenience store for 18 years resists everyone's idea of normal.",
    tags: ["literary_fiction", "japanese_literature", "workplace", "convenience_store", "short_read", "quirky", "satire"],
    pop: 0.75, cities: { tokyo: 0.7 }, fans: ["severance", "fleabag", "the-office"], by: "Sayaka Murata",
  },
  {
    key: "ja/before-the-coffee", name: "Before the Coffee Gets Cold", kind: "book", year: 2015,
    original: ["コーヒーが冷めないうちに", "ja"],
    desc: "In a small Tokyo café, customers can travel back in time, but only until their coffee cools.",
    tags: ["fantasy", "japanese_literature", "time_travel", "coffee", "cozy", "gentle"],
    pop: 0.75, cities: { tokyo: 0.7 }, fans: ["gilmore-girls", "bake-off"], by: "Toshikazu Kawaguchi",
  },
  {
    key: "ja/norwegian-wood", name: "Norwegian Wood", kind: "book", year: 1987,
    original: ["ノルウェイの森", "ja"],
    desc: "A Tokyo student in the late 1960s is torn between two very different young women.",
    tags: ["literary_fiction", "japanese_literature", "romance", "coming_of_age", "melancholic", "nostalgic"],
    pop: 0.85, cities: { tokyo: 0.8 }, fans: ["normal-people"], by: "Haruki Murakami",
  },
  {
    key: "ja/sweet-bean-paste", name: "Sweet Bean Paste", kind: "book", year: 2013,
    original: ["あん", "ja"],
    desc: "The novel behind the film 'Sweet Bean': a dorayaki seller learns patience from an elderly woman.",
    tags: ["literary_fiction", "japanese_literature", "food", "gentle", "melancholic"],
    pop: 0.45, fans: ["bake-off", "kitchen-confidential"], by: "Durian Sukegawa",
  },
  {
    key: "ja/library", name: "What You Are Looking For Is in the Library", kind: "book", year: 2020,
    original: ["お探し物は図書室まで", "ja"],
    desc: "A Tokyo librarian's odd book suggestions nudge five people toward a change in their lives.",
    tags: ["literary_fiction", "japanese_literature", "library", "workplace", "cozy", "gentle"],
    pop: 0.55, cities: { tokyo: 0.6 }, fans: ["gilmore-girls", "normal-people"], by: "Michiko Aoyama",
  },
  {
    key: "ja/travelling-cat", name: "The Travelling Cat Chronicles", kind: "book", year: 2012,
    original: ["旅猫リポート", "ja"],
    desc: "A man and his cat, Nana, drive across Japan to visit old friends.",
    tags: ["literary_fiction", "japanese_literature", "cats", "friendship", "warm", "melancholic"],
    pop: 0.6, fans: ["gilmore-girls", "bake-off"], by: "Hiro Arikawa",
  },
  // Podcasts
  {
    key: "ja/nihongo-con-teppei", name: "Nihongo con Teppei", kind: "podcast",
    desc: "Short, slow episodes of everyday Japanese talk for beginners.",
    tags: ["language_learning", "japanese_language"],
    pop: 0.6,
  },
  {
    key: "ja/yuyu", name: "YUYU no Nihongo Podcast", kind: "podcast",
    original: ["YUYUの日本語Podcast", "ja"],
    desc: "Natural Japanese talk about culture and daily life, for intermediate learners.",
    tags: ["language_learning", "japanese_language"],
    pop: 0.45,
  },
  {
    key: "ja/noriko", name: "Learn Japanese with Noriko", kind: "podcast",
    desc: "A Japanese teacher talks about daily life in plain Japanese.",
    tags: ["language_learning", "japanese_language"],
    pop: 0.4,
  },
  // Restaurants (London)
  {
    key: "ja/koya", name: "Koya", kind: "place", city: "London", address: "Soho, London",
    desc: "Soho udon counter making noodles in house, served hot or cold.",
    tags: ["japanese", "udon"], pop: 0.7, fans: ["the-bear", "kitchen-confidential"],
  },
  {
    key: "ja/kanada-ya", name: "Kanada-Ya", kind: "place", city: "London", address: "Covent Garden, London",
    desc: "Ramen shop known for rich tonkotsu broth.",
    tags: ["japanese", "ramen"], pop: 0.65, fans: ["the-bear"],
  },
  {
    key: "ja/bone-daddies", name: "Bone Daddies", kind: "place", city: "London", address: "Soho, London",
    desc: "Loud, casual ramen bar with rock on the stereo.",
    tags: ["japanese", "ramen"], pop: 0.6, fans: ["the-bear", "frank-ocean"],
  },
  {
    key: "ja/roka", name: "Roka", kind: "place", city: "London", address: "Fitzrovia, London",
    desc: "Robata grill restaurant built around a central charcoal grill.",
    tags: ["japanese", "izakaya", "sushi"], pop: 0.6, fans: ["succession"],
  },
];
