import type { CatalogItem } from "./types";

const KR = ["South Korea"];

export const KOREAN: CatalogItem[] = [
  // Series
  {
    key: "ko/hometown-cha-cha-cha", name: "Hometown Cha-Cha-Cha", kind: "tv_show", year: 2021, countries: KR, rating: "TV-14", minutes: 75,
    original: ["갯마을 차차차", "ko"],
    desc: "A big-city dentist opens a practice in a seaside village and clashes with its jack-of-all-trades local.",
    local: ["바닷가 마을을 배경으로 한 로맨틱 코미디", "ko"],
    tags: ["romantic_comedy", "romance", "small_town", "seaside", "cozy", "warm"],
    pop: 0.85, cities: { seoul: 0.8, busan: 0.75 }, fans: ["gilmore-girls", "pride-and-prejudice"],
  },
  {
    key: "ko/reply-1988", name: "Reply 1988", kind: "tv_show", year: 2015, finale: 2016, countries: KR, rating: "TV-14", minutes: 90,
    original: ["응답하라 1988", "ko"],
    desc: "Five families on one Seoul alley in 1988 share meals, rivalries and first loves.",
    tags: ["comedy", "drama", "family", "friendship", "nostalgia", "coming_of_age", "cozy", "warm"],
    pop: 0.85, cities: { seoul: 0.9, busan: 0.8 }, fans: ["gilmore-girls"],
  },
  {
    key: "ko/hospital-playlist", name: "Hospital Playlist", kind: "tv_show", year: 2020, finale: 2021, countries: KR, rating: "TV-14", minutes: 90,
    original: ["슬기로운 의사생활", "ko"],
    desc: "Five doctors who have been friends since medical school work at one hospital and play in a band.",
    tags: ["drama", "comedy", "hospital", "friendship", "workplace", "music", "warm"],
    pop: 0.8, cities: { seoul: 0.85, busan: 0.75 }, fans: ["gilmore-girls", "the-bear", "the-office"],
  },
  {
    key: "ko/attorney-woo", name: "Extraordinary Attorney Woo", kind: "tv_show", year: 2022, countries: KR, rating: "TV-14", minutes: 70,
    original: ["이상한 변호사 우영우", "ko"],
    desc: "A brilliant autistic lawyer starts work at a big Seoul law firm.",
    tags: ["drama", "comedy", "lawyer", "workplace", "warm"],
    pop: 0.85, cities: { seoul: 0.9, busan: 0.8 }, fans: ["gilmore-girls", "ted-lasso"],
  },
  {
    key: "ko/twenty-five-twenty-one", name: "Twenty-Five Twenty-One", kind: "tv_show", year: 2022, countries: KR, rating: "TV-14", minutes: 70,
    original: ["스물다섯 스물하나", "ko"],
    desc: "A teenage fencer and a young man who lost everything grow up together in the late 1990s.",
    tags: ["romance", "drama", "coming_of_age", "sports", "nostalgic", "melancholic"],
    pop: 0.75, cities: { seoul: 0.8, busan: 0.7 }, fans: ["normal-people", "taylor-swift"],
  },
  {
    key: "ko/our-beloved-summer", name: "Our Beloved Summer", kind: "tv_show", year: 2021, finale: 2022, countries: KR, rating: "TV-14", minutes: 60,
    original: ["그 해 우리는", "ko"],
    desc: "Exes who were filmed for a school documentary ten years ago are pushed into making a sequel.",
    tags: ["romantic_comedy", "romance", "nostalgia", "melancholic", "warm"],
    pop: 0.7, cities: { seoul: 0.75, busan: 0.65 }, fans: ["normal-people", "gilmore-girls", "pride-and-prejudice"],
  },
  {
    key: "ko/samdal-ri", name: "Welcome to Samdal-ri", kind: "tv_show", year: 2023, finale: 2024, countries: KR, rating: "TV-14", minutes: 70,
    original: ["웰컴투 삼달리", "ko"],
    desc: "A famous photographer goes home to Jeju after a scandal and runs into her childhood friend.",
    tags: ["romantic_comedy", "small_town", "seaside", "family", "cozy"],
    pop: 0.6, cities: { seoul: 0.6, busan: 0.55 }, fans: ["gilmore-girls"],
  },
  {
    key: "ko/youns-kitchen", name: "Youn's Kitchen", kind: "tv_show", year: 2017, countries: KR, rating: "TV-G", minutes: 80,
    original: ["윤식당", "ko"],
    desc: "Korean actors run a small restaurant on an island abroad for a few weeks.",
    tags: ["reality", "cooking_show", "food", "cozy", "gentle"],
    pop: 0.55, cities: { seoul: 0.7, busan: 0.6 }, fans: ["bake-off", "the-bear"],
  },
  {
    key: "ko/culinary-class-wars", name: "Culinary Class Wars", kind: "tv_show", year: 2024, countries: KR, rating: "TV-14", minutes: 70,
    original: ["흑백요리사: 요리 계급 전쟁", "ko"],
    desc: "Eighty little-known cooks take on twenty star chefs in a huge cooking competition.",
    tags: ["reality", "cooking_show", "competition", "food", "chef"],
    pop: 0.8, cities: { seoul: 0.9, busan: 0.85 }, fans: ["bake-off", "the-bear", "kitchen-confidential"],
  },
  {
    key: "ko/business-proposal", name: "Business Proposal", kind: "tv_show", year: 2022, countries: KR, rating: "TV-14", minutes: 60,
    original: ["사내맞선", "ko"],
    desc: "A woman goes on a blind date in her friend's place and finds out her date is her new CEO.",
    tags: ["romantic_comedy", "comedy", "workplace", "upbeat"],
    pop: 0.75, cities: { seoul: 0.75, busan: 0.7 }, fans: ["gilmore-girls", "taylor-swift"],
  },
  {
    key: "ko/my-mister", name: "My Mister", kind: "tv_show", year: 2018, countries: KR, rating: "TV-14", minutes: 75,
    original: ["나의 아저씨", "ko"],
    desc: "A worn-out engineer and a young temp worker with a hard past quietly look out for each other.",
    tags: ["drama", "workplace", "grief", "melancholic", "slow_burn"],
    pop: 0.75, cities: { seoul: 0.85, busan: 0.75 }, fans: ["severance", "fleabag", "normal-people"],
  },
  // Films
  {
    key: "ko/little-forest", name: "Little Forest", kind: "movie", year: 2018, countries: KR, rating: "NR", minutes: 103,
    original: ["리틀 포레스트", "ko"],
    desc: "A young woman leaves Seoul for her childhood village and cooks her way through the seasons.",
    tags: ["drama", "food", "cooking", "small_town", "slow_burn", "cozy", "gentle"],
    pop: 0.6, cities: { seoul: 0.7, busan: 0.6 }, fans: ["bake-off", "the-bear", "kitchen-confidential"], by: "Yim Soon-rye",
  },
  {
    key: "ko/parasite", name: "Parasite", kind: "movie", year: 2019, countries: KR, rating: "R", minutes: 132,
    original: ["기생충", "ko"],
    desc: "A poor family schemes its way into jobs with a rich household until the plan unravels.",
    tags: ["thriller", "dark_comedy", "satire", "wealth", "tense"],
    pop: 0.97, cities: { seoul: 0.9, busan: 0.85 }, fans: ["succession", "knives-out", "severance"], by: "Bong Joon-ho",
  },
  {
    key: "ko/decision-to-leave", name: "Decision to Leave", kind: "movie", year: 2022, countries: KR, rating: "NR", minutes: 138,
    original: ["헤어질 결심", "ko"],
    desc: "A detective investigating a man's fall from a mountain becomes drawn to the dead man's wife.",
    tags: ["mystery", "romance", "thriller", "slow_burn", "stylish"],
    pop: 0.7, cities: { seoul: 0.7, busan: 0.65 }, fans: ["knives-out", "orient-express"], by: "Park Chan-wook",
  },
  {
    key: "ko/tune-in-for-love", name: "Tune in for Love", kind: "movie", year: 2019, countries: KR, rating: "NR", minutes: 122,
    original: ["유열의 음악앨범", "ko"],
    desc: "Two people keep finding and losing each other over a decade, linked by a radio music show.",
    tags: ["romance", "drama", "nostalgia", "music", "melancholic"],
    pop: 0.55, cities: { seoul: 0.6 }, fans: ["normal-people", "taylor-swift"],
  },
  {
    key: "ko/my-sassy-girl", name: "My Sassy Girl", kind: "movie", year: 2001, countries: KR, rating: "NR", minutes: 123,
    original: ["엽기적인 그녀", "ko"],
    desc: "A timid student is swept into the chaotic life of a bold young woman he meets on the subway.",
    tags: ["romantic_comedy", "comedy", "romance", "quirky"],
    pop: 0.7, cities: { seoul: 0.7, busan: 0.65 }, fans: ["gilmore-girls"],
  },
  {
    key: "ko/train-to-busan", name: "Train to Busan", kind: "movie", year: 2016, countries: KR, rating: "NR", minutes: 118,
    original: ["부산행", "ko"],
    desc: "Passengers on a high-speed train from Seoul fight to survive a sudden zombie outbreak.",
    tags: ["horror", "thriller", "survival", "tense"],
    pop: 0.9, cities: { busan: 0.85, seoul: 0.8 }, fans: ["stranger-things", "breaking-bad"], by: "Yeon Sang-ho",
  },
  // Artists
  {
    key: "ko/iu", name: "IU", kind: "artist",
    original: ["아이유", "ko"],
    desc: "Singer-songwriter and actor whose ballads and pop songs have topped Korean charts since 2010.",
    tags: ["k_pop", "k_ballad", "singer_songwriter", "romantic", "warm"],
    pop: 0.95, cities: { seoul: 0.95, busan: 0.9 }, fans: ["taylor-swift", "phoebe-bridgers"],
  },
  {
    key: "ko/akmu", name: "AKMU", kind: "artist",
    original: ["악뮤", "ko"],
    desc: "Brother-and-sister duo writing bright, clever acoustic pop.",
    tags: ["k_pop", "k_indie", "singer_songwriter", "upbeat", "quirky"],
    pop: 0.8, cities: { seoul: 0.85, busan: 0.8 }, fans: ["taylor-swift"],
  },
  {
    key: "ko/10cm", name: "10CM", kind: "artist",
    original: ["십센치", "ko"],
    desc: "Indie singer known for soft, funny acoustic love songs.",
    tags: ["k_indie", "singer_songwriter", "romantic", "gentle"],
    pop: 0.65, cities: { seoul: 0.8, busan: 0.7 }, fans: ["phoebe-bridgers", "taylor-swift"],
  },
  {
    key: "ko/bol4", name: "BOL4", kind: "artist",
    original: ["볼빨간사춘기", "ko"],
    desc: "Acoustic pop act with sweet, diary-like songs about crushes and growing up.",
    tags: ["k_indie", "k_pop", "romantic", "upbeat"],
    pop: 0.7, cities: { seoul: 0.8, busan: 0.75 }, fans: ["taylor-swift"],
  },
  {
    key: "ko/day6", name: "DAY6", kind: "artist",
    desc: "Pop-rock band that writes and plays its own songs, known for big, emotional choruses.",
    tags: ["k_pop", "k_rock", "indie_rock", "romantic"],
    pop: 0.8, cities: { seoul: 0.9, busan: 0.85 }, fans: ["taylor-swift", "phoebe-bridgers"],
  },
  {
    key: "ko/newjeans", name: "NewJeans", kind: "artist",
    desc: "Girl group known for breezy, Y2K-flavored pop songs like 'Hype Boy' and 'Ditto'.",
    tags: ["k_pop", "pop", "upbeat", "dreamy"],
    pop: 0.9, cities: { seoul: 0.9, busan: 0.85 }, fans: ["taylor-swift", "billie-eilish"],
  },
  {
    key: "ko/taeyeon", name: "Taeyeon", kind: "artist",
    original: ["태연", "ko"],
    desc: "Girls' Generation leader with a solo career of polished pop ballads.",
    tags: ["k_pop", "k_ballad", "romantic"],
    pop: 0.8, cities: { seoul: 0.85, busan: 0.8 }, fans: ["taylor-swift"],
  },
  {
    key: "ko/crush", name: "Crush", kind: "artist",
    original: ["크러쉬", "ko"],
    desc: "R&B singer and producer with a smooth, warm voice.",
    tags: ["korean_rnb", "rnb", "romantic"],
    pop: 0.7, cities: { seoul: 0.8, busan: 0.7 }, fans: ["frank-ocean"],
  },
  {
    key: "ko/heize", name: "Heize", kind: "artist",
    original: ["헤이즈", "ko"],
    desc: "Singer-songwriter blending R&B and hip-hop with wistful lyrics.",
    tags: ["korean_rnb", "rnb", "melancholic"],
    pop: 0.65, cities: { seoul: 0.75, busan: 0.65 }, fans: ["frank-ocean", "phoebe-bridgers"],
  },
  {
    key: "ko/lee-hi", name: "Lee Hi", kind: "artist",
    original: ["이하이", "ko"],
    desc: "Singer with a deep, soulful voice known for slow ballads like 'Breathe'.",
    tags: ["k_ballad", "korean_rnb", "melancholic"],
    pop: 0.6, cities: { seoul: 0.75, busan: 0.65 }, fans: ["phoebe-bridgers", "frank-ocean"],
  },
  {
    key: "ko/bts", name: "BTS", kind: "artist",
    desc: "Seven-member group that became the best-known K-pop act in the world.",
    tags: ["k_pop", "pop", "upbeat"],
    pop: 0.98, cities: { seoul: 0.95, busan: 0.95 }, fans: ["taylor-swift"],
  },
  // Books
  {
    key: "ko/hyunam-dong", name: "Welcome to the Hyunam-dong Bookshop", kind: "book", year: 2022,
    original: ["어서 오세요, 휴남동 서점입니다", "ko"],
    desc: "A woman who burned out at work opens a small bookshop in a quiet Seoul neighborhood.",
    tags: ["literary_fiction", "korean_literature", "bookshop", "workplace", "cozy", "gentle"],
    pop: 0.65, cities: { seoul: 0.8 }, fans: ["gilmore-girls", "pride-and-prejudice"], by: "Hwang Bo-reum",
  },
  {
    key: "ko/dallergut", name: "The Dallergut Dream Department Store", kind: "book", year: 2020,
    original: ["달러구트 꿈 백화점", "ko"],
    desc: "In a town where people shop for dreams while they sleep, a new employee learns the trade.",
    tags: ["fantasy", "korean_literature", "dreams", "workplace", "cozy", "whimsical"],
    pop: 0.65, cities: { seoul: 0.8 }, fans: ["harry-potter", "spirited-away", "gilmore-girls"], by: "Lee Mi-ye",
  },
  {
    key: "ko/almond", name: "Almond", kind: "book", year: 2017,
    original: ["아몬드", "ko"],
    desc: "A teenage boy who can't feel fear or anger forms an unlikely friendship with a troubled classmate.",
    tags: ["young_adult", "coming_of_age", "literary_fiction", "korean_literature", "introspective"],
    pop: 0.7, cities: { seoul: 0.7 }, fans: ["normal-people"], by: "Sohn Won-pyung",
  },
  {
    key: "ko/look-after-mom", name: "Please Look After Mom", kind: "book", year: 2008,
    original: ["엄마를 부탁해", "ko"],
    desc: "A mother goes missing in a crowded Seoul station, and her family realizes how little they knew her.",
    tags: ["literary_fiction", "korean_literature", "family", "grief", "melancholic"],
    pop: 0.6, cities: { seoul: 0.6 }, fans: ["normal-people", "fleabag"], by: "Shin Kyung-sook",
  },
  {
    key: "ko/hen", name: "The Hen Who Dreamed She Could Fly", kind: "book", year: 2000,
    original: ["마당을 나온 암탉", "ko"],
    desc: "A hen escapes her coop and raises a duckling as her own.",
    tags: ["fable", "korean_literature", "short_read", "gentle"],
    pop: 0.55, fans: ["spirited-away", "bake-off"], by: "Hwang Sun-mi",
  },
  // Podcasts
  {
    key: "ko/ttmik", name: "Talk To Me In Korean", kind: "podcast",
    desc: "Bite-size Korean lessons from a Seoul team of teachers, from absolute basics up.",
    tags: ["language_learning", "korean_language"],
    pop: 0.6,
  },
  {
    key: "ko/iyagi", name: "TTMIK Iyagi", kind: "podcast",
    desc: "Unscripted conversations in Korean between teachers about daily life.",
    tags: ["language_learning", "korean_language"],
    pop: 0.4,
  },
  // Restaurants (Toronto)
  {
    key: "ko/korean-village", name: "Korean Village Restaurant", kind: "place", city: "Toronto", address: "Koreatown, Toronto",
    desc: "Long-running Koreatown restaurant for barbecue, stews and banchan.",
    tags: ["korean", "korean_bbq"], pop: 0.6, fans: ["the-bear"],
  },
  {
    key: "ko/buk-chang-dong", name: "Buk Chang Dong Soon Tofu", kind: "place", city: "Toronto", address: "Koreatown, Toronto",
    desc: "Koreatown spot for bubbling soft tofu stew, ordered by spice level.",
    tags: ["korean"], pop: 0.6, fans: ["bake-off", "gilmore-girls"],
  },
  {
    key: "ko/owl-of-minerva", name: "Owl of Minerva", kind: "place", city: "Toronto", address: "Koreatown, Toronto",
    desc: "Late-night Korean restaurant known for pork bone soup.",
    tags: ["korean"], pop: 0.55, fans: ["the-bear"],
  },
];
